### ISSUE TITLE
多参数如何处理

### ISSUE THREAD

**Issue by hhhaiai** [zhouat/Inject-Hook#3]
多个参数如何处理？

**Comment by zheking1** [comment]
XposedHelpers.findAndHookMethod(
                        "android.content.Intent",
                        loadPackageParam.classLoader,
                        "getIntExtra",
                        **String.class,**
                        **`int.class,`**
                        new XC_MethodHook() {
                            @Override
                            protected void beforeHookedMethod(MethodHookParam param)
                                    throws Throwable {
                                Intent intent = (Intent) param.thisObject;
                                final String action = intent.getAction();
                                if (action.equals(Intent.ACTION_BATTERY_CHANGED)) {
                                    if (BatteryManager.EXTRA_LEVEL.equals(param.args[0] + "")) {
                                        param.setResult(1);
                                    } else if (BatteryManager.EXTRA_PLUGGED.equals(param.args[0] + "")) {
                                        XposedBridge.log("batteryPlugged");
                                        param.setResult(0);
                                    }
                                }
                            }

                            @Override
                            protected void afterHookedMethod(MethodHookParam param)
                                    throws Throwable {
                            }
                        }
                );

**Comment by hhhaiai** [comment]
3Q

**Comment by hhhaiai** [comment]
好多年前问的了。 多谢
